//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCenter_testApp_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class artykul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public artykul()
        {
            this.dokument_artykul = new HashSet<dokument_artykul>();
        }
    
        public int ar_id { get; set; }
        public string ar_nazwa { get; set; }
        public Nullable<int> ar_liczba { get; set; }
        public Nullable<decimal> ar_cena_netto { get; set; }
        public Nullable<decimal> ar_cena_brutto { get; set; }
        public Nullable<System.DateTime> ar_aud_data { get; set; }
        public string ar_aud_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dokument_artykul> dokument_artykul { get; set; }
    }
}
