//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCenter_testApp_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class dokument_artykul
    {
        public int nar_id { get; set; }
        public int nar_ar_id { get; set; }
        public int nar_do_id { get; set; }
        public Nullable<System.DateTime> nar_aud_data { get; set; }
        public string nar_aud_login { get; set; }
    
        public virtual artykul artykul { get; set; }
        public virtual dokument_naglowek dokument_naglowek { get; set; }
    }
}
