//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCenter_testApp_IS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class col_dataEntities : DbContext
    {
        public col_dataEntities()
            : base("name=col_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artykul> artykul { get; set; }
        public virtual DbSet<dokument_artykul> dokument_artykul { get; set; }
        public virtual DbSet<dokument_naglowek> dokument_naglowek { get; set; }
    
        public virtual int p_int_artkul_dodaj(string p_ar_nazwa, Nullable<int> p_ar_liczba, Nullable<decimal> p_ar_cena_br, Nullable<decimal> p_ar_cena_nt)
        {
            var p_ar_nazwaParameter = p_ar_nazwa != null ?
                new ObjectParameter("p_ar_nazwa", p_ar_nazwa) :
                new ObjectParameter("p_ar_nazwa", typeof(string));
    
            var p_ar_liczbaParameter = p_ar_liczba.HasValue ?
                new ObjectParameter("p_ar_liczba", p_ar_liczba) :
                new ObjectParameter("p_ar_liczba", typeof(int));
    
            var p_ar_cena_brParameter = p_ar_cena_br.HasValue ?
                new ObjectParameter("p_ar_cena_br", p_ar_cena_br) :
                new ObjectParameter("p_ar_cena_br", typeof(decimal));
    
            var p_ar_cena_ntParameter = p_ar_cena_nt.HasValue ?
                new ObjectParameter("p_ar_cena_nt", p_ar_cena_nt) :
                new ObjectParameter("p_ar_cena_nt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_int_artkul_dodaj", p_ar_nazwaParameter, p_ar_liczbaParameter, p_ar_cena_brParameter, p_ar_cena_ntParameter);
        }
    
        public virtual int p_int_artkul_update(string p_ar_ids, Nullable<decimal> p_ar_cena_brutto, Nullable<decimal> p_ar_cena_netto, Nullable<int> par_liczba, string p_ar_nazwa)
        {
            var p_ar_idsParameter = p_ar_ids != null ?
                new ObjectParameter("p_ar_ids", p_ar_ids) :
                new ObjectParameter("p_ar_ids", typeof(string));
    
            var p_ar_cena_bruttoParameter = p_ar_cena_brutto.HasValue ?
                new ObjectParameter("p_ar_cena_brutto", p_ar_cena_brutto) :
                new ObjectParameter("p_ar_cena_brutto", typeof(decimal));
    
            var p_ar_cena_nettoParameter = p_ar_cena_netto.HasValue ?
                new ObjectParameter("p_ar_cena_netto", p_ar_cena_netto) :
                new ObjectParameter("p_ar_cena_netto", typeof(decimal));
    
            var par_liczbaParameter = par_liczba.HasValue ?
                new ObjectParameter("par_liczba", par_liczba) :
                new ObjectParameter("par_liczba", typeof(int));
    
            var p_ar_nazwaParameter = p_ar_nazwa != null ?
                new ObjectParameter("p_ar_nazwa", p_ar_nazwa) :
                new ObjectParameter("p_ar_nazwa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_int_artkul_update", p_ar_idsParameter, p_ar_cena_bruttoParameter, p_ar_cena_nettoParameter, par_liczbaParameter, p_ar_nazwaParameter);
        }
    
        public virtual int p_int_artkul_usun(string p_ar_ids)
        {
            var p_ar_idsParameter = p_ar_ids != null ?
                new ObjectParameter("p_ar_ids", p_ar_ids) :
                new ObjectParameter("p_ar_ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_int_artkul_usun", p_ar_idsParameter);
        }
    
        public virtual int p_int_dokument_artkul_dodaj(string p_ar_ids, Nullable<int> p_do_id)
        {
            var p_ar_idsParameter = p_ar_ids != null ?
                new ObjectParameter("p_ar_ids", p_ar_ids) :
                new ObjectParameter("p_ar_ids", typeof(string));
    
            var p_do_idParameter = p_do_id.HasValue ?
                new ObjectParameter("p_do_id", p_do_id) :
                new ObjectParameter("p_do_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_int_dokument_artkul_dodaj", p_ar_idsParameter, p_do_idParameter);
        }
    
        public virtual ObjectResult<p_int_dokument_artykul_pobierz_Result> p_int_dokument_artykul_pobierz(Nullable<int> p_do_id)
        {
            var p_do_idParameter = p_do_id.HasValue ?
                new ObjectParameter("p_do_id", p_do_id) :
                new ObjectParameter("p_do_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_int_dokument_artykul_pobierz_Result>("p_int_dokument_artykul_pobierz", p_do_idParameter);
        }
    
        public virtual int p_int_dokument_dodaj(string p_do_nazwa, Nullable<System.DateTime> p_do_data, string p_do_numer_kl, Nullable<decimal> p_do_cena_br, Nullable<decimal> p_do_cena_nt)
        {
            var p_do_nazwaParameter = p_do_nazwa != null ?
                new ObjectParameter("p_do_nazwa", p_do_nazwa) :
                new ObjectParameter("p_do_nazwa", typeof(string));
    
            var p_do_dataParameter = p_do_data.HasValue ?
                new ObjectParameter("p_do_data", p_do_data) :
                new ObjectParameter("p_do_data", typeof(System.DateTime));
    
            var p_do_numer_klParameter = p_do_numer_kl != null ?
                new ObjectParameter("p_do_numer_kl", p_do_numer_kl) :
                new ObjectParameter("p_do_numer_kl", typeof(string));
    
            var p_do_cena_brParameter = p_do_cena_br.HasValue ?
                new ObjectParameter("p_do_cena_br", p_do_cena_br) :
                new ObjectParameter("p_do_cena_br", typeof(decimal));
    
            var p_do_cena_ntParameter = p_do_cena_nt.HasValue ?
                new ObjectParameter("p_do_cena_nt", p_do_cena_nt) :
                new ObjectParameter("p_do_cena_nt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_int_dokument_dodaj", p_do_nazwaParameter, p_do_dataParameter, p_do_numer_klParameter, p_do_cena_brParameter, p_do_cena_ntParameter);
        }
    
        public virtual ObjectResult<p_int_dokument_pobierz_Result> p_int_dokument_pobierz(Nullable<int> p_do_id)
        {
            var p_do_idParameter = p_do_id.HasValue ?
                new ObjectParameter("p_do_id", p_do_id) :
                new ObjectParameter("p_do_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_int_dokument_pobierz_Result>("p_int_dokument_pobierz", p_do_idParameter);
        }
    
        public virtual int p_int_dokument_update(string p_do_ids, Nullable<decimal> p_do_cen_br, Nullable<decimal> p_do_cen_nt, string p_do_nazwa, string p_do_nr_kli, Nullable<System.DateTime> p_do_data)
        {
            var p_do_idsParameter = p_do_ids != null ?
                new ObjectParameter("p_do_ids", p_do_ids) :
                new ObjectParameter("p_do_ids", typeof(string));
    
            var p_do_cen_brParameter = p_do_cen_br.HasValue ?
                new ObjectParameter("p_do_cen_br", p_do_cen_br) :
                new ObjectParameter("p_do_cen_br", typeof(decimal));
    
            var p_do_cen_ntParameter = p_do_cen_nt.HasValue ?
                new ObjectParameter("p_do_cen_nt", p_do_cen_nt) :
                new ObjectParameter("p_do_cen_nt", typeof(decimal));
    
            var p_do_nazwaParameter = p_do_nazwa != null ?
                new ObjectParameter("p_do_nazwa", p_do_nazwa) :
                new ObjectParameter("p_do_nazwa", typeof(string));
    
            var p_do_nr_kliParameter = p_do_nr_kli != null ?
                new ObjectParameter("p_do_nr_kli", p_do_nr_kli) :
                new ObjectParameter("p_do_nr_kli", typeof(string));
    
            var p_do_dataParameter = p_do_data.HasValue ?
                new ObjectParameter("p_do_data", p_do_data) :
                new ObjectParameter("p_do_data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_int_dokument_update", p_do_idsParameter, p_do_cen_brParameter, p_do_cen_ntParameter, p_do_nazwaParameter, p_do_nr_kliParameter, p_do_dataParameter);
        }
    
        public virtual int p_int_dokument_usun(string p_do_ids)
        {
            var p_do_idsParameter = p_do_ids != null ?
                new ObjectParameter("p_do_ids", p_do_ids) :
                new ObjectParameter("p_do_ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_int_dokument_usun", p_do_idsParameter);
        }
    }
}
